#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

compact_path="docs/llms.txt"
full_path="docs/llms-full.txt"

cat > "$compact_path" <<'EOF'
# scalarian-openai-rust / llms.txt

`scalarian-openai-rust` is an independent Rust SDK for the OpenAI API. The GitHub repository is `scalarian/openai-rust`, while the Rust crate import path remains `openai_rust`.

## Canonical entry points

- `README.md`: project overview, quickstart, crate map, contribution and release pointers.
- `docs/quickstart.md`: first-use commands and a minimal live request.
- `docs/responses-guide.md`: Responses-first guidance for structured outputs and streaming.
- `docs/migration-guide.md`: migration notes for chat-completions and legacy completions users.
- `docs/files-and-vector-stores.md`: file uploads, vector stores, and retrieval flows.
- `docs/architecture-note.md`: runtime, transport, and realtime design notes.
- `docs/api-coverage.md`: surface-by-surface capability map.
- `docs/intentional-gaps.md`: unsupported or intentionally deferred areas.
- `docs/maintenance.md`: local validation commands and release-facing checks.

## Crate map

- `openai_rust::OpenAI`: top-level client builder and request preparation.
- `openai_rust::resources`: typed REST API families.
- `openai_rust::realtime`: realtime session and event models.
- `openai_rust::helpers`: multipart, pagination, SSE, structured output, and webhook helpers.
- `openai_rust::blocking`: feature-gated blocking facade.

## Representative examples

- `examples/responses_quickstart.rs`
- `examples/responses_streaming.rs`
- `examples/structured_outputs.rs`
- `examples/request_metadata.rs`
- `examples/embeddings.rs`
- `examples/upload_to_vector_store.rs`
- `examples/chat_completions_migration.rs`

## Validation commands

```sh
cargo fmt --all --check
cargo test --workspace
cargo check --examples --all-features
cargo test --doc
docs/scripts/check_links.sh
docs/scripts/generate_llms_exports.sh
cargo package --workspace --allow-dirty --no-verify
```
EOF

{
    cat <<'EOF'
# scalarian-openai-rust / llms-full.txt

This file is generated by `docs/scripts/generate_llms_exports.sh`.
It concatenates the public project entry points that are useful for LLM-oriented retrieval.

EOF

    for file in \
        README.md \
        CODE_OF_CONDUCT.md \
        SECURITY.md \
        SUPPORT.md \
        CHANGELOG.md \
        docs/quickstart.md \
        docs/responses-guide.md \
        docs/migration-guide.md \
        docs/files-and-vector-stores.md \
        docs/architecture-note.md \
        docs/api-coverage.md \
        docs/intentional-gaps.md \
        docs/maintenance.md; do
        printf -- '---\nFILE: %s\n---\n\n' "$file"
        cat "$file"
        printf '\n\n'
    done
} > "$full_path"
